### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by orschiro** [gerane/language-todotxt#4]
Dear @gerane,

Thank you for creating this package. I would like to have TODO syntax highlighting, too. 

Thus, I installed the package but I don't see any highlighting. See this example:

![image](https://cloud.githubusercontent.com/assets/170947/10266842/a23bf19c-6a79-11e5-926b-b62b5e3c0226.png)

Could you please provide me with a screenshot so that I can see how it is supposed to look like?

Thankfully,

Robert

**Comment by spoike** [comment]
This package is not for highlighting "TODOs". It's a syntax highlighter for todo.txt files. There is a website that documents the format of these txt files over here: http://todotxt.com/

The todo.txt files are basically task lists and a couple of rows may look like this:

```todotxt
x 2015-11-09 Did the stuff
Movie night with wife @home #movie
Buy snacks for #movie night @store
(A) Implement flurb #project @work
Meet with Steve @lunch
```

**Comment by gerane** [comment]
Sorry, I have been writing a lot of Powershell lately and using a more Powershell oriented editor. I have not been able to use Atom as much as I had in the past. As @spoike mentioned, this is more for todo.txt todo lists. There is a package that does what you are looking for and can be found here: https://atom.io/packages/language-todo

**Comment by orschiro** [comment]
Dear @spoike @gerane,

It's more clear to me now. Sorry for the confusion and thanks for the further references!

~ Robert
